// demos/client-angular-example/src/app/app.component.ts
// Copyright 2021-2025 Prosopo (UK) Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
import { Component, OnInit } from "@angular/core";
import { FormBuilder, FormGroup, Validators } from "@angular/forms";

@Component({
	selector: "app-root",
	templateUrl: "./app.component.html",
	styleUrls: ["./app.component.css"],
})
export class AppComponent implements OnInit {
	siteKey = "5C7bfXYwachNuvmasEFtWi9BMS41uBvo6KpYHVSQmad4nWzw"; // Replace with your actual site key
	captchaToken: string | null = null;
	submitted = false;
	form!: FormGroup;

	constructor(private fb: FormBuilder) {}

	ngOnInit(): void {
		this.initForm();
	}

	initForm(): void {
		this.form = this.fb.group({
			name: ["", Validators.required],
			email: ["", [Validators.required, Validators.email]],
		});
	}

	onCaptchaVerified(token: string): void {
		console.log("Captcha verified with token:", token);
		this.captchaToken = token;
	}

	onCaptchaExpired(): void {
		console.log("Captcha expired");
		this.captchaToken = null;
	}

	onCaptchaFailed(): void {
		console.log("Captcha failed");
		this.captchaToken = null;
	}

	onCaptchaLoaded(): void {
		console.log("Captcha loaded");
	}

	onSubmit(): void {
		if (this.form.valid && this.captchaToken) {
			console.log("Form submitted with captcha token:", this.captchaToken);
			console.log("Form values:", this.form.value);
			this.submitted = true;
		} else {
			// Mark all fields as touched to trigger validation messages
			this.form.markAllAsTouched();
			if (!this.captchaToken) {
				console.error("Cannot submit form without captcha verification");
			}
		}
	}

	get formControls() {
		return this.form.controls;
	}
}

<div class="container">
  <h1>Simple Form Demo</h1>
  <form [formGroup]="form" (ngSubmit)="onSubmit()">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" formControlName="name">
      <div *ngIf="formControls['name'].invalid && (formControls['name'].dirty || formControls['name'].touched)" class="error-message">
        <div *ngIf="formControls['name'].errors?.['required']">Name is required.</div>
      </div>
    </div>
    
    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" class="form-control" id="email" formControlName="email">
      <div *ngIf="formControls['email'].invalid && (formControls['email'].dirty || formControls['email'].touched)" class="error-message">
        <div *ngIf="formControls['email'].errors?.['required']">Email is required.</div>
        <div *ngIf="formControls['email'].errors?.['email']">Please enter a valid email address.</div>
      </div>
    </div>
    
    <div class="form-group">
      <h3>Procaptcha Widget:</h3>
      <prosopo-captcha 
        [siteKey]="siteKey"
        [theme]="'light'"
        [captchaType]="'frictionless'"
        (verified)="onCaptchaVerified($event)"
        (expired)="onCaptchaExpired()"
        (failed)="onCaptchaFailed()"
        (loaded)="onCaptchaLoaded()">
      </prosopo-captcha>
      <div *ngIf="!captchaToken && submitted" class="error-message">
        Please complete the captcha verification.
      </div>
    </div>
    
    <button type="submit" [disabled]="form.invalid || !captchaToken">Submit</button>
  </form>
  
  <div *ngIf="submitted" class="success-message">
    <h2>Form submitted successfully!</h2>
    <p><strong>Name:</strong> {{ form.value.name }}</p>
    <p><strong>Email:</strong> {{ form.value.email }}</p>
    <p><strong>Captcha Token:</strong> {{ captchaToken }}</p>
  </div>
</div>

// demos/client-pow-example/src/App.tsx
// Copyright 2021-2024 Prosopo (UK) Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { EnvironmentTypes, EnvironmentTypesSchema, ProsopoClientConfigSchema } from '@prosopo/types'
import { ProcaptchaPow } from '@prosopo/procaptcha-pow'
import { useState, useRef, useEffect } from 'react'

function App() {
    const [account, setAccount] = useState<string>('')
    const config = ProsopoClientConfigSchema.parse({
        userAccountAddress: account,
        account: {
            address: process.env.PROSOPO_SITE_KEY || '',
        },
        web2: process.env.PROSOPO_WEB2 === 'true',
        dappName: 'client-example',
        defaultEnvironment:
            (process.env.PROSOPO_DEFAULT_ENVIRONMENT as EnvironmentTypes) || EnvironmentTypesSchema.enum.development,
        serverUrl: process.env.PROSOPO_SERVER_URL || '',
        atlasUri: process.env._DEV_ONLY_WATCH_EVENTS === 'true' || false,
    })

    const formRef = useRef<HTMLFormElement>(null)

    useEffect(() => {
        const form = formRef.current

        if (form) {
            const handleSubmit = async (event: Event) => {
                event.preventDefault()
                console.log('Form submitted:', form)

                console.log('Dummy form submission with data:', event)
            }

            form.addEventListener('submit', handleSubmit)

            return () => {
                form.removeEventListener('submit', handleSubmit)
            }
        }
        return
    }, [])

    return (
        <div style={{ height: '100%', display: 'block', justifyContent: 'center', alignItems: 'center' }}>
            <form ref={formRef}>
                <div>
                    <label htmlFor="name">Name:</label>
                    <input type="text" id="name" name="name" required />
                </div>
                <div>
                    <label htmlFor="email">Email:</label>
                    <input type="email" id="email" name="email" required />
                </div>
                <ProcaptchaPow config={config} />
                <button type="submit">Submit</button>
            </form>
        </div>
    )
}

export default App
