// integration/frameworks/react/react-procaptcha-integration-demo/src/integrationDemo.tsx
// Copyright 2021-2025 Prosopo (UK) Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { ProcaptchaComponent } from "@prosopo/react-procaptcha-wrapper";
import type { ReactNode } from "react";

const IntegrationDemoComponent = (): ReactNode => {
	// @ts-expect-error Env variables will be read by Vite
	const siteKey = import.meta.env.VITE_PROCAPTCHA_SITE_KEY || "";

	return (
		<ProcaptchaComponent
			siteKey={siteKey}
			captchaType={"pow"}
			language={"en"}
			callback={(token: string): void => {
				console.log("verified", token);
			}}
			htmlAttributes={{
				className: "my-app__procaptcha",
				style: {
					maxWidth: "600px",
				},
			}}
		/>
	);
};

export { IntegrationDemoComponent };

// integration/frameworks/vue/vue-procaptcha-integration-demo/src/integrationDemo.vue
<template>
 <ProcaptchaComponent :siteKey="siteKey"
                      captchaType="pow"
                      language="en"
                      :callback="(token: string): void => {
                        console.log('verified', token)
                        }"
                      :htmlAttributes="{class:'my-app__procaptcha'}"/>
</template>

<script setup lang="ts">
import {ProcaptchaComponent} from "@prosopo/vue-procaptcha-wrapper";

// @ts-expect-error Env variables will be read by Vite
const siteKey = import.meta.env.VITE_PROCAPTCHA_SITE_KEY || "";
</script>
