// integrations/vue/vue-procaptcha-wrapper/src/procaptchaComponent.vue
<script setup lang="ts">
import {onMounted, onUpdated, useTemplateRef} from "vue";

import {HTMLAttributes} from "vue"
import {type ProcaptchaOptions, procaptchaWrapper} from "@prosopo/procaptcha-wrapper";

type ProcaptchaComponentProperties = ProcaptchaOptions & {
  htmlAttrs: AllHtmlAttributes,
}

type AllHtmlAttributes = HTMLAttributes & {
  // allow custom data attributes
  [key: string]: any
};

const properties = defineProps<ProcaptchaComponentProperties>();
const wrapper = useTemplateRef("wrapper");

// refuse unregistered properties.
defineOptions({
  inheritAttrs: false
});

onMounted(() => {
  renderProcaptcha();
});
onUpdated(() => {
  renderProcaptcha();
});

function renderProcaptcha(): void {
  const wrapperElement = wrapper.value;

  if (wrapperElement instanceof HTMLElement) {
    procaptchaWrapper.renderProcaptcha(wrapperElement, properties);
  }
}
</script>

<template>
  <div ref="wrapper"></div>
</template>

// integration/frameworks/svelte/svelte-procaptcha-wrapper/src/procaptchaComponent.svelte
<script lang="ts">
    import {tick, onMount} from "svelte";
    import type {HTMLAttributes} from "svelte/elements";
    import {type ProcaptchaOptions, procaptchaWrapper} from "@prosopo/procaptcha-wrapper";

    type ProcaptchaComponentProperties = ProcaptchaOptions & {
        htmlAttrs?: AllHtmlAttributes,
    }

    type AllHtmlAttributes = HTMLAttributes<HTMLElement> & {
        // allow custom data attributes
        [key: string]: any
    };

    const properties: ProcaptchaComponentProperties = $props();
    const htmlWrapperElementAttributes = $derived(properties.htmlAttrs || {});
    let wrapperElement: HTMLDivElement;

    onMount(() => {
        tick().then(() => {
            procaptchaWrapper.renderProcaptcha(wrapperElement, properties);
        });
    });
</script>

<div bind:this={wrapperElement} {...htmlWrapperElementAttributes}></div>
